### ISSUE TITLE
don't know

### ISSUE THREAD

**Issue by Alfinkresna64** [Chr0m0s0m3s/DeadTrapv2#14]
I got this error after I run python main.py, I tried several ways, starting from installing pillow separately and trying to reinstall it but also keep error like this : 
WARNING: linker: /data/data/com.termux/files/usr/lib/python3.8/site-packages/PIL/_imaging.cpython-38.so: unused DT entry: type 0x6ffffef5 arg 0xd28
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import osint.fb as fb
  File "/data/data/com.termux/files/home/DeadTrapv2/osint/fb.py", line 3, in <module>
    from PIL import Image
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: dlopen failed: cannot locate symbol "modf" referenced by "/data/data/com.termux/files/usr/lib/python3.8/site-packages/PIL/_imaging.cpython-38.so"...

**Comment by jakuta-tech** [comment]
Hi, maybe just run this to see the versions that you have on your system.
 
`pip3 freeze | grep "google\|pyfiglet\|Pillow\|bs4\|argparse\|phonenumbers"`

It will do a printout like this.

```
pip3 freeze | grep "google\|pyfiglet\|Pillow\|bs4\|argparse\|phonenumbers"
bs4==0.0.1
google==3.0.0
phonenumbers==8.12.13
Pillow==7.2.0
pyfiglet==0.8.post1
```

you can also use pip show to see the package details 

```
pip show argparse
Name: argparse
Version: 1.4.0
Summary: Python command-line parsing library
Home-page: https://github.com/ThomasWaldmann/argparse/
Author: Thomas Waldmann
Author-email: tw@waldmann-edv.de
License: Python Software Foundation License
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: smtp-user-enum
```
