### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lilcsz** [Chr0m0s0m3s/DeadTrapv2#7]
File "main.py", line 5, in <module>
    from scanners.numVerifyscan import numverifyScan
  File "/home/lilcsz/DeadTrapv2/scanners/numVerifyscan.py", line 18, in <module>
    def numverifyScan(num, secret=api_generate()):
  File "/home/lilcsz/DeadTrapv2/scanners/numVerifyscan.py", line 10, in api_generate
    soup = BeautifulSoup(r.text, "html5lib")
  File "/home/lilcsz/.local/lib/python3.7/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?

**Comment by Chr0m0s0m3s** [comment]
sry have to add that to requirements.txt
```pip install html5lib```

**Comment by MR-pentestGuy** [comment]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from scanners.basicScan import libphonenumbers

**Comment by MR-pentestGuy** [comment]
ModuleNotFoundError: No module named 'phonenumbers'

**Comment by MR-pentestGuy** [comment]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from scanners.fraud import *
ImportError: No module named scanners.fraud

**Comment by lilcsz** [comment]
Thanks
